### PR TITLE
New GIFs in 'adorbs/Oops'

### PR DESCRIPTION
**Pull request by seefood**

### CODE REVIEW

**Comment by seefood** [comment]
I have ~900 GIFs in my own collection, so I can either send you a PR per directory and you adopt the ones you like, or I can just let you pull from me at your free time. I have a feeling you may not appreciate 83 PRs, so I'll stop at two examples :-)

**Comment by snipe** [comment]
Would these maybe make more sense in the `doing-it-wrong` directory? `adorns` was basically meant as a generic "I need something adorable" directory.

**Comment by seefood** [comment]
I'm fine with that, it's just that the directory started by me collecting your existing adorbs into funny animal accidents. The taxonomy is yours and not written in stone :)

**Comment by snipe** [comment]
Eww, why are you using buy real name here? PR DENIED.

**Comment by seefood** [comment]
Oops, sorry... I didn't know you were separating identities here :(

**Comment by snipe** [comment]
I was kidding - it’s all good :)

**Pull request merged**
