### PR TITLE
Removed dupes using fdupes -r

### PR DESCRIPTION
**Pull request by seefood**
In the next PRs I mean to rename files that are random unique strings to meaningful ones, finally maybe re-sort and add my own. Let me know if you are interested in PRs for those.

### CODE REVIEW

**Comment by snipe** [comment]
I'm not familiar with fdupes - have you visually confirmed that there were no false positives?

**Comment by ira-lb** [comment]
fdupes finds dupes by doing a tree walk and hashing all files by size, then visiting all buckets with more than one file (that are not hardlinks) and compares md5. it's quite solid :-)

I took the output it gave and manually picked which copy to remove. preference was meaningful name over a unique junk string, and sorted directory over root (I think in two cases I moved the meaningful name from the root to the subdir and removed the meaningless-named one from the subdir, so it's a win-win)

**Comment by ira-lb** [comment]
oops, replied from my work user :) still me though...

**Comment by snipe** [comment]
Awesome, thanks!

**Comment by snipe** [comment]
(I've been manually giving them meaningful names when I have time, but there are a lot)

**Comment by seefood** [comment]
I know, Juggling work and life is hard enough :)

I'll be renaming and sorting some when I have free time (also juggling family and startup life...)

**Pull request merged**
